codecov:
  require_ci_to_pass: yes

coverage:
  status:
    patch: false
    project:
      default:
        # basic
        informational: true
        target: auto
        threshold: 100%

  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "flagship/src/main/java/com/abtasty/flagship/database"