# This is a basic workflow to help you get started with Actions

name: CI UnitTest & Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
          cache-read-only: true
      - name: Clean
        run: ./gradlew :flagship:clean
      - name: Build with Gradle
        run: ./gradlew :flagship:assembleDebug
#      - name: Unit tests
#        run: bash ./gradlew flagship:testJacocoUnitTestCoverage -i --stacktrace
#      - name: Generate report
#        run: bash ./gradlew flagship:createJacocoUnitTestCoverageReport
      - name: Unit tests
        run: bash ./gradlew flagship:jacocoDebugCodeCoverage -i --stacktrace
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: flagship/build/reports/jacoco/jacocoDebugCodeCoverage/jacocoDebugCodeCoverage.xml
      - name: Build
        run: bash ./gradlew flagship:clean flagship:assembleRelease
