# This is a basic workflow to help you get started with Actions

name: CI UnitTest & Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '#ci-auto') == false
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Unit tests
        run: bash ./gradlew flagship:testAllVariantsWithCoverage
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          files: flagship/build/reports/jacoco/testCommonDebugUnitTestCoverage/testCommonDebugUnitTestCoverage.xml
      - name: Build
        run: bash ./gradlew flagship:clean flagship:assembleRelease
