name: CI Release
# run UT, Build, Publish
on:
  push:
    tags:
      - '*.*.*'
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '#ci-auto') == false
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "17"
      - name: Unit tests
        run: bash ./gradlew clean flagship:testJacocoUnitTestCoverage
      - name: Get version
        run: |
          echo "FLAGSHIP_VERSION_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          files:
            flagship/build/jacocoHtml/index.xml
      - name: Build and Publish
        env:
          SONATYPE_SIGNING_KEY: ${{ secrets.SONATYPE_SIGNING_KEY }}
          SONATYPE_SIGNING_PWD: ${{ secrets.SONATYPE_SIGNING_PWD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_REPOSITORY: ${{ secrets.SONATYPE_REPOSITORY }}
        run: |
          bash ./gradlew clean
          bash ./gradlew flagship:assembleRelease
          bash ./gradlew publishToSonatype closeSonatypeStagingRepository
          bash ./gradlew publishToSonatype -Dvariant=compat closeSonatypeStagingRepository
