name: CI Release
# run UT, Build, Publish
on:
  push:
    tags:
      - '*.*.*'
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
          cache-read-only: true
      - name: Clean
        run: ./gradlew :flagship:clean
      - name: Build with Gradle
        run: ./gradlew :flagship:assembleDebug
      - name: Unit tests
        run: bash ./gradlew flagship:testJacocoUnitTestCoverage -i --stacktrace
      - name: Generate report
        run: bash ./gradlew flagship:createJacocoUnitTestCoverageReport
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: flagship/build/reports/coverage/test/jacoco/report.xml
      - name: Build and Publish
        env:
          SONATYPE_SIGNING_KEY: ${{ secrets.SONATYPE_SIGNING_KEY }}
          SONATYPE_SIGNING_PWD: ${{ secrets.SONATYPE_SIGNING_PWD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_REPOSITORY: ${{ secrets.SONATYPE_REPOSITORY }}
        run: |
          bash ./gradlew clean
          bash ./gradlew flagship:assembleRelease
          bash ./gradlew publishToSonatype closeSonatypeStagingRepository
