name: CI Release
# run UT, Build, Publish
on:
  push:
    tags:
      - '*.*.*'
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
          cache-read-only: true
      - name: Clean
        run: ./gradlew :flagship:clean
      - name: Build with Gradle
        run: ./gradlew :flagship:assembleDebug
      - name: Unit tests
        id: unit_tests
        continue-on-error: true
        run: bash ./gradlew flagship:jacocoDebugCodeCoverage -i --stacktrace
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: flagship/build/reports/tests/testDebugUnitTest/
      - name: Stop if tests failed
        if: steps.unit_tests.conclusion == 'failure'
        run: exit 1
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: flagship/build/reports/jacoco/jacocoDebugCodeCoverage/jacocoDebugCodeCoverage.xml
      - name: Build and Publish
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME}}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
        run: |
          bash ./gradlew clean
          bash ./gradlew flagship:assembleRelease
          bash ./gradlew publishToMavenCentral --stacktrace
